#此为GPS数据量检测程序的配置文件，用于配置发送短信的对象，格式为"phone: 电话号码"，多个号码之间使用英语的:分隔
#注意phone:后有一个空格
phone: 18810650391:13051355646

#以下是数据库信息配置，用于检测数据库的可用性，其中ip、user、passwd后边的信息是一一对应的，顺序不能弄错
db:
    ip: [192.168.2.109, 192.168.2.113]
    user: [root, root]
    passwd: [123456, 123456]