# 邮件的配置文件
[SMTP]
host = "smtp.163.com"
list = ['605760635@qq.com', '154589878@qq.com']
user = "gaoming971366"
pwd = "625125301"
postfix = "163.com"

#数据库的配置信息
[DATABASE]
type = 1
server = "127.0.0.1"
port = 3306
db = "test"
user = "root"
pwd = "123456"

#数据源的配置信息
[SOURCE]
data = "E:\\data\\ws\\data"