# 实际的配置文件请把此文件复制后改名，再行修改，不要直接修改此文件，并且保证每台机器一个文件
# 该设备ip地址
ip: 192.168.2.121
# 设备操作系统类型
ostype: win7

# 设备的SNMP配置
snmp:
  enable: 1
  community: public
  version: 1
  port: 161

# 远程桌面信息，如果可用enable设为1，不可用设为0
rdp:
  enable: 0
  user: root
  password: hello
  port: 3389

# ssh信息
ssh:
  enable: 0
  user: root
  password: root
  port: 22

# 数据库信息，如果该节点没有数据库则enable设为0
database:
  enable: 1
  type: mysql
  port: 3306
  user: root
  password: 123456
  default: wz_traffic

# 需要检查的信息, 例如数据库、进程、硬盘；硬盘的目录信息要注意大小写
checkitems:
  - hd:
    - path: D:\\
      warnning: 80
      description: GPS folder
  - db:
    - alias: Total05m
      dbName: wz_traffic
      delay: 300
      sql: select time from total05m order by time desc limit 1